[NoInterfaceObject] interface SpeechManagerObject {
        readonly attribute SpeechManager speech;
};

Tizen implements SpeechManagerObject;

[NoInterfaceObject] interface SpeechManager {
    void vocalizeString(DOMString speakString);
};
